// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `iceInterfaces.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.onek.server.inf;

/**
 * 服务接口 interface
 **/
public interface Interfaces extends Ice.Object,
                                    _InterfacesOperations, _InterfacesOperationsNC
{
    public static final String ice_staticId = "::inf::Interfaces";

    public static final long serialVersionUID = -47023542L;
}
